[tool.cibuildwheel]
# Skip building PyPy version as not specifically validated/tested yet
# Alpine linux is musslinux.  Takes long time to generate.  Will add if requested
skip = ["pp*", "*-musllinux*"]

[tool.cibuildwheel.linux]
before-all = "yum -y install flex bison cmake"

# cibuildwheel docker environment for python 3.7 has old OpenSSL
# requests installs latest urllib3 which will not work with it
test-skip = ["cp37-manylinux_x86_64", "cp37-manylinux_i686"]

test-command = 'python -c "from mmcif.io.IoAdapterCore import IoAdapterCore as IoAdapter"'

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add flex bison cmake"